# Generated by Django 3.2.12 on 2024-06-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='blog',
            field=models.CharField(default='https://main--scrumming-it.netlify.app/posts/ruby-on-rails/', max_length=250),
        ),
    ]
