# Generated by Django 3.2.12 on 2024-07-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_demo_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='git',
            field=models.CharField(default='https://github.com/heidless-stillwater/', max_length=250),
        ),
    ]
