# Generated by Django 3.2.12 on 2024-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
