# Generated by Django 3.2.12 on 2024-06-27 15:08

import datasciences.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.FileField(upload_to='icons', validators=[datasciences.validators.validate_file_extension])),
            ],
            options={
                'verbose_name': 'DataScience',
                'verbose_name_plural': 'DataSciences',
            },
        ),
    ]
