# Generated by Django 3.2.12 on 2024-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='git',
            field=models.CharField(default='https://github.com/heidless-stillwater/', max_length=250),
        ),
    ]
