# Generated by Django 3.2.12 on 2024-06-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='blog',
            field=models.CharField(default='blog link', max_length=250),
        ),
    ]
