# Generated by Django 3.2.12 on 2024-06-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_sample_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='blog',
            field=models.CharField(default='https://www.amazon.co.uk/', max_length=250),
        ),
    ]
