# Generated by Django 3.2.12 on 2024-07-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_sample_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='git',
            field=models.CharField(default='https://github.com/heidless-stillwater/', max_length=250),
        ),
    ]
